services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - cat-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4543:8080"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    networks:
      - cat-network

networks:
  cat-network:
    driver: bridge