name: Update Cats

on:
  push:
    branches: [main]

jobs:
  update_cats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to my registry
      #   run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login registry.floxsite.de -u flo --password-stdin

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: registry.floxsite.de
          username: flo
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & Push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: registry.floxsite.de/cats-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: registry.floxsite.de/cats-frontend:latest

      # - name: Build & Push API
      #   run: |
      #     docker buildx build --platform linux/arm64,linux/amd64 -t registry.floxsite.de/cats-backend:latest --push ./api

      # - name: Build & Push Frontend
      #   run: |
      #     docker buildx build --platform linux/arm64,linux/amd64 -t registry.floxsite.de/cats-frontend:latest --push ./api

      # - name: SSH into Raspberry Pi and pull changes
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.PI_HOST }}
      #     username: ${{ secrets.PI_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /home/pi/Deployed/KodzenLog
      #       git pull
      #       make build
